media:
  input: assets/images
  output: assets/images
  template: "/beta-website/{path}"
  extensions:
    - jpg
    - jpeg
    - png
    - gif
    - svg
    - pdf

content:
  # Team Management
  - name: team
    label: Team Members
    path: _data/team.yml
    type: file
    fields:
      - name: members
        label: Team Members
        type: object
        list: true
        fields:
          - name: name
            label: Name
            type: string
            required: true
          - name: role
            label: Role
            type: string
            required: true
          - name: image
            label: Profile Image
            type: image
            required: true
          - name: expertise
            label: Expertise
            type: string
            list: true
          - name: email
            label: Email
            type: string
            required: true
          - name: animation_delay
            label: Animation Delay
            type: number
            default: 0.1

  # Projects Management
  - name: projects
    label: Projects
    path: _data/projects.yml
    type: file
    fields:
      - name: items
        label: Projects
        type: object
        list: true
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: tag
            label: Tag (Smart City, Open Innovation, Künstliche Intelligenz, Innovation Lab, E-Government, Data Analytics)
            type: string
            required: true
          - name: description
            label: Description
            type: text
            required: true
          - name: status
            label: Status (Im Live-Betrieb, Umgesetzt, Gestartet, Umsetzung, Planung, Beta)
            type: string
            required: true
          - name: start_date
            label: Start Date
            type: date
            required: true
          - name: responsible
            label: Responsible Person
            type: string
            required: true
          - name: link
            label: Link
            type: string
          - name: link_text
            label: Link Text
            type: string

  # Events Management
  - name: events
    label: Events
    path: _data/events.yml
    type: file
    fields:
      - name: items
        label: Events
        type: object
        list: true
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: description
            label: Description
            type: text
            required: true
          - name: date
            label: Date
            type: date
            required: true
          - name: time
            label: Time
            type: string
            required: true
          - name: duration
            label: Duration
            type: string
          - name: location
            label: Location
            type: string
            required: true
          - name: category
            label: Category (Workshop, Meetup, Vortrag, Konferenz, Networking)
            type: string
            required: true
          - name: icon
            label: Icon
            type: image
          - name: target_audience
            label: Target Audience
            type: string
            required: true
          - name: cost
            label: Cost
            type: string
            default: Kostenlos
          - name: booking_url
            label: Booking URL
            type: string
          - name: featured
            label: Featured
            type: boolean
            default: false

  # Blog Posts
  - name: blog
    label: Blog Posts
    path: _beitraege
    type: collection
    extension: md
    create: true
    filename: "{{title | slugify}}"
    fields:
      - name: title
        label: Title
        type: text
        required: true
      - name: teaser
        label: Teaser
        type: textarea
        required: true
      - name: author
        label: Author (Jens Edler, Tajana Džepina, Maria Gonçalves, Lisa Meyer, Sarah Bollmann, Stephan Berkowitz)
        type: string
        required: true
      - name: category
        label: Category (Tools, Projekte, News, Workshop, Event)
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: header_image
        label: Header Image
        type: image
        media: assets/images
      - name: body
        label: Content
        type: rich-text
        required: true

